export type Epg = {
  start: string;
  end: string;
  days: number[];
  name: string;
  description: string;
};


export const Epgs = [

  {
    start: "07:00",
    end: "08:00",
    days: [1, 2, 3, 4, 5],
    name: "Desperta ICL",
    description:"Sem informações",
  },
  {
    start: "08:00",
    end: "10:00",
    days: [1, 2, 3, 4, 5],
    name: "ICL Notícias 1",
    description:"Sem informações",
  },
  {
    start: "10:00",
    end: "11:00",
    days: [1, 2, 3, 4, 5],
    name: "Em Destalhes",
    description:"Sem informações",
  },
  {
    start: "11:00",
    end: "11:30",
    days: [1, 2, 3, 4, 5],
    name: "ICL Mercados e Investimentos",
    description:"Sem informações",
  },
  {
    start: "11:30",
    end: "12:30",
    days: [1, 2, 3, 4, 5],
    name: "Rolê ICL",
    description:"Sem informações",
  },
  {
    start: "12:30",
    end: "13:30",
    days: [1, 2, 3, 4, 5, 6],
    name: "Bem Melhor",
    description:"Programa de variedades voltado ao Universo da gastronomia, viagens, turismo e bem estar! Apresentado por Flávio Júnior.",
  },
  {
    start: "13:00",
    end: "14:00",
    days: [1, 2, 3, 4, 5, 6],
    name: "Pet Lovers Cast",
    description:"",
  },
  {
    start: "14:00",
    end: "16:00",
    days: [1, 2, 3, 4, 5, 6],
    name: "Matinê Pop TV",
    description:"Melhores Filmes que marcaram época, grandes clássicos do cinema, comédias, aventuras, musicais, romances e muito mais!",
  },
  {
    start: "16:00",
    end: "17:30",
    days: [1, 2, 3, 4, 5, 6],
    name: "Sessão Retrô",
    description:"A Sessão Retrô é uma faixa que apresenta séries atuais e clássicas que marcaram época na TV.",
  },
  {
    start: "18:00",
    end: "19:30",
    days: [1, 2, 3, 4, 5],
    name: "ICL Notícias Noite",
    description:"Sem informações",
  },
  {
    start: "19:30",
    end: "20:00",
    days: [1],
    name: "Em Destalhes",
    description:"Sem informações",
  },
  {
    start: "20:00",
    end: "20:30",
    days: [2],
    name: "Em Destalhes",
    description:"Sem informações",
  },
  {
    start: "21:30",
    end: "22:00",
    days: [3],
    name: "Em Destalhes",
    description:"Sem informações",
  },
  {
    start: "20:30",
    end: "21:00",
    days: [4,5],
    name: "Em Destalhes",
    description:"Sem informações",
  },
  {
    start: "20:00",
    end: "21:00",
    days: [1],
    name: "Chico Pinheiro Entrevista",
    description:"Sem informações",
  },
  {
    start: "01:00",
    end: "02:00",
    days: [2],
    name: "Chico Pinheiro Entrevista - Reprise",
    description:"Sem informações",
  },
  {
    start: "21:00",
    end: "22:00",
    days: [1],
    name: "Desperta ICL - Reprise",
    description:"Sem informações",
  },
  {
    start: "20:30",
    end: "21:30",
    days: [2],
    name: "Desperta ICL - Reprise",
    description:"Sem informações",
  },
  {
    start: "19:30",
    end: "20:30",
    days: [4, 5],
    name: "Desperta ICL - Reprise",
    description:"Sem informações",
  },
  {
    start: "22:00",
    end: "22:30",
    days: [1, 4],
    name: "ICL Mercados e Investimentos - Reprise",
    description:"Sem informações",
  },
  {
    start: "21:30",
    end: "22:00",
    days: [2],
    name: "ICL Mercados e Investimentos - Reprise",
    description:"Sem informações",
  },
  {
    start: "23:00",
    end: "23:30",
    days: [3],
    name: "ICL Mercados e Investimentos - Reprise",
    description:"Sem informações",
  },
  {
    start: "21:00",
    end: "21:30",
    days: [5],
    name: "ICL Mercados e Investimentos - Reprise",
    description:"Sem informações",
  },
  {
    start: "22:30",
    end: "23:30",
    days: [1, 2, 3, 4, 5],
    name: "Rolê ICL - Reprise",
    description:"Sem informações",
  },
  {
    start: "22:00",
    end: "23:00",
    days: [2, 3],
    name: "Rolê ICL - Reprise",
    description:"Sem informações",
  },
  {
    start: "21:00",
    end: "22:00",
    days: [4],
    name: "Rolê ICL - Reprise",
    description:"Sem informações",
  },
  {
    start: "21:30",
    end: "22:30",
    days: [4],
    name: "Rolê ICL - Reprise",
    description:"Sem informações",
  },
  {
    start: "23:30",
    end: "23:59",
    days: [1, 3],
    name: "ICL Notícias Noite - Reprise",
    description:"Sem informações",
  },
  {
    start: "00:00",
    end: "01:00",
    days: [2, 4],
    name: "ICL Notícias Noite - Reprise",
    description:"Sem informações",
  },  
  {
    start: "23:00",
    end: "23:59",
    days: [2, 4],
    name: "ICL Notícias Noite - Reprise",
    description:"Sem informações",
  },
  {
    start: "00:00",
    end: "00:30",
    days: [3, 5],
    name: "ICL Notícias Noite - Reprise",
    description:"Sem informações",
  }, 
  {
    start: "22:00",
    end: "23:59",
    days: [5],
    name: "ICL Notícias Noite - Reprise",
    description:"Sem informações",
  },
  {
    start: "19:30",
    end: "20:00",
    days: [2],
    name: "Espiritualidade Na Ação",
    description:"Sem informações",
  },
  {
    start: "19:30",
    end: "20:30",
    days: [3],
    name: "Provocação Histórica",
    description:"Sem informações",
  },
  {
    start: "08:00",
    end: "10:30",
    days: [6],
    name: "Manhã Criança",
    description:"Sem informações",
  },
  {
    start: "06:00",
    end: "06:30",
    days: [2, 5],
    name: "Hora do Scooby-Doo",
    description:"Sem informações",
  },
  {
    start: "10:30",
    end: "12:00",
    days: [6],
    name: "Cinema - Primeira Sessão",
    description:"Sem informações",
  },
  {
    start: "18:00",
    end: "20:45",
    days: [6, 7],
    name: "Fest Series",
    description:"Sem informações",
  },
    {
    start: "06:30",
    end: "07:00",
    days: [1, 2, 3, 4, 5],
    name: "Compilação Clipes",
    description: "Sem informações",
  },

];